version: "3.8"
name: woodytoys
services:
  resolver:
    build: ./resolv
    container_name: resolver
    depends_on:
      - soa
    networks:
      woodytoys:
        ipv4_address: 192.168.0.6
  soa:
    build: ./soa
    container_name: soa
    networks:
      woodytoys:
        ipv4_address: 192.168.0.5
  mail:
    build: ./mail
    container_name: mail
    networks:
      woodytoys:
        ipv4_address: 192.168.0.4
  web:
    build: ./web
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - db
    #volumes:
    #  - ./web/html
    networks:
      woodytoys:
        ipv4_address: 192.168.0.2
  db:
    build: ./db
    container_name: DB
    networks:
      woodytoys:
        ipv4_address: 192.168.0.3
  user1:
    build: ./user1
    container_name: user1
    networks:
      woodytoys:
        ipv4_address: 192.168.0.7

  
networks:
  woodytoys:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
