version: "3.8"
name: woodytoys_publique
services: 
  soa_publique:
    build: ./soa_publique
    container_name: soa_publique
    networks:
      woodytoys:
        ipv4_address: 192.168.1.5

  
networks:
  woodytoys:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
