version: "3.8"
name: woodytoys_publique
services:
  web:
    build: ./web
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - db
    #volumes:
    #  - ./web/html
    networks:
      woodytoys:
        ipv4_address: 192.168.1.2

  
networks:
  woodytoys:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
