FROM ubuntu:latest

RUN apt update

RUN apt-get install -y postfix
RUN apt-get install -y dovecot-imapd 
RUN apt-get install -y dovecot-pop3d
RUN apt-get install -y dovecot-core


RUN apt-get install -y nmap
RUN apt-get install -y nano
RUN apt-get install -y net-tools
RUN apt-get install -y telnet


COPY dovecot.conf /etc/dovecot/
COPY main.cf /etc/postfix/

CMD service postfix start && service dovecot start && tail -f /dev/null